repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-toml
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.10
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-black
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-check-blanket-noqa
- repo: https://github.com/timothycrosley/isort
  rev: 5.9.3
  hooks:
  - id: isort
-   repo: https://github.com/ikamensh/flynt/
    rev: '0.69'
    hooks:
    -   id: flynt
        args: [
            '--line-length=120',
            '--fail-on-change',
        ]
- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear==20.1.4
    - flake8-builtins==1.5.3
    - flake8-comprehensions==3.2.3
    - flake8-rst-docstrings==0.0.14
    - flake8-markdown==0.2.0
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        pass_filenames: true
